addpath('./bgc1d_src/');
addpath('./optimization/');
addpath('./processing/');
addpath('./runscripts/');
addpath('./Data/');
addpath('./restart/');
addpath('./saveOut/');
addpath('./functions/');
addpath('./optimOut/');
